name: ci

on:
  push:
    branches: main

jobs:
  login:
    runs-on: self-hosted
    steps:
      -
        name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
